spring.application.name=Todolist2

# ===================================================================
# データベース接続設定
# ===================================================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
